### ISSUE TITLE
Is there a problem uploading the code on NPM? There is no code in the NPM package

### ISSUE THREAD

**Issue by lilian132** [PrudhviBanki/react-native-pk-wifi-reborn#1]
Is there a problem uploading the code on NPM? There is no code in the NPM package

**Comment by PrudhviBanki** [comment]
Not Yet.

Are you facing any issue?

**Comment by lilian132** [comment]
> Is there a problem uploading the code on NPM? There is no code in the NPM package

I saw your NPM package on the NPM website and wanted to test its usability, but after installing NPM, I found that there is no valid code inside
![微信截图_20230824140706](https://github.com/PrudhviBanki/react-native-pk-wifi-reborn/assets/4987042/f97a51a2-ee16-4669-85f2-24f106c3c019)
